[yownload]
#polite_test ansible_host=89.23.98.20 ansible_user=root ansible_ssh_private_key_file=~/.ssh/polite_root
#honest_nether ansible_host=72.56.70.228 ansible_user=root ansible_ssh_private_key_file=~/.ssh/honest_root
#dh-germ1 ansible_host=193.233.198.126 ansible_user=root ansible_ssh_private_key_file=~/.ssh/dh-germ-1
time_germ ansible_host=5.42.127.98 ansible_user=root ansible_ssh_private_key_file=~/.ssh/nimble_root