---
zsh_theme: afowler
configure_root_zsh: true

omz_plugins_base:
  - git
  - history
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - dirhistory
  - web-search
  - docker
  - extract
  - docker-compose
  - z
  - fzf
  - colored-man-pages
  - aliases
  - ansible

pip_packages_base:
  - httpie

pipx_packages_base: []

# При true добавляет thefuck к плагинам Oh My Zsh и устанавливает его через pip/pipx
enable_thefuck: false

omz_plugins: "{{ omz_plugins_base + (enable_thefuck | bool | ternary(['thefuck'], [])) }}"
pip_packages: "{{ pip_packages_base + (enable_thefuck | bool | ternary(['thefuck'], [])) }}"
pipx_packages: "{{ pipx_packages_base + (enable_thefuck | bool | ternary(['thefuck'], [])) }}"

base_packages:
  - git
  - curl
  - wget
  - nano
  - zsh
  - fzf
  - unzip
  - python3
  - python3-pip
  - rsync
  - sshpass
  - ansible-core
  - htop
  - net-tools

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

# будут скачаны из репозиториев
zsh_custom_plugins:
  - name: zsh-autosuggestions
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    version: master

  - name: zsh-syntax-highlighting
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    version: master
