---
yusic_worker_relay_packages:
  - skopeo
  - sshpass
yusic_worker_relay_root_dir: /opt/yusic-worker-relay
yusic_worker_relay_archive_dir: "{{ yusic_worker_relay_root_dir }}/archives"
yusic_worker_relay_stage_dir: "{{ yusic_worker_relay_root_dir }}/stage"
